spring:
  application:
    name: priceradar

  datasource:
    url: jdbc:postgresql://localhost:5432/priceradar
    driver-class-name: org.postgresql.Driver
    username: priceradar
    password: priceradar

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

priceradar:
  mock-data-file: data/mock-prices.csv

